### ISSUE TITLE
読んだ！以外のボタン時もmodalを出すようにする

### ISSUE THREAD

**Issue by chanchihiro** [nippoly/nippoly#13]
## やること
- [x] まとめる！を押した時「読んだものをCBにまとめました」を出す
- [x] 削除する！を押した時「読んだものを削除しました」を出す
- [x] 新しいmodalを出した時前のmodalが消えるようにする（読んだ！を二回押してしまった時もちゃんと消す）
- [x] まとめる押した時にポップアップ消えちゃうのを押しても残しておくようにする

## 理由
反応がないとユーザーが不安になる。何個もmodal溜まっちゃうの嫌だ。

## どんな感じか
modalに挿入してるDOMをボタン押すごとに空欄にしてから新しいDOM入れるみたいなことすればできるはず？汚いかもだけど笑
頼んだ！
デザインで必要なものあれば言ってください

**Comment by touyou** [comment]
JavaScriptでそのIDがあるかどうか判断する関数みたいなんある？？

**Comment by chanchihiro** [comment]
わからんけどありそう！
