### ISSUE TITLE
リリースブログ

### ISSUE THREAD

**Issue by s11y** [nippoly/nippoly#5]
## やること
リリースのブログと、lit-nippoとはなんなのかをはてブかmediumで書く
## 理由
なんで作ったのか？何をしているのか？誰がやったのか？どれだけ面白いか？をまとめたい。周知したい。
## TODO
リリースに間に合うように書く

**Comment by chanchihiro** [comment]
あざす！

**Comment by chanchihiro** [comment]
書いたからdone
